sudo: required
services:
  - docker

before_install:
  - docker build -t garrettforsyth/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true garrettforsyth/react-test npm test

after_success:
  - docker build -t garrettforsyth/multi-client ./client
  - docker build -t garrettforsyth/multi-nginx ./nginx
  - docker build -t garrettforsyth/multi-server ./server
  - docker build -t garrettforsyth/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push these images to docker hub
  - docker push garrettforsyth/multi-client
  - docker push garrettforsyth/multi-nginx
  - docker push garrettforsyth/multi-server
  - docker push garrettforsyth/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-278393663359
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
